authentication/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import home,signIn,signUp
from django.utils.translation import gettext_lazy as _
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^signIn/$',signIn,name="signIn"),
    url(r'^signUp/$',signUp,name="signUp"),
    url(r'^',home,name="home")
]

jd_builder/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.utils.translation import gettext_lazy as _
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    url(r'^admin/$', include(admin.site.urls)),
    #url(r'social-auth/$',include('social.apps.django_app.urls', namespace='social')),
    url(r'^', include('authentication.urls', namespace="authentication")),

]

authentication/models.py
from django.db.models import CharField,IntegerField,DateField,Model,AutoField

# Create your models here.

class UserPasswordTable(Model):
    UserId=AutoField(primary_key=True)
    UserName=CharField(max_length=100)
    UserEmail=CharField(max_length=50,primary_key=True)
    Password1=CharField(max_length=20)

    def __str__(self):
        return self.UserId

authentication/forms.py
from django.forms import ModelForm
from .models import UserPasswordTable
from django import forms
from django.forms import Form


class SignUpForm(Form):
    Email=forms.CharField(widget=forms.TextInput(
        attrs={
        'class':'form-control',
        'id':'password',
        'placeholder':'Enter Email Address'
        }
    ))

    Name=forms.CharField(widget=forms.TextInput(
        attrs={
        'class':'form-control',
        'id':'password',
        'placeholder':'Enter Full Name'
        }
    ))
    Password=forms.CharField(widget=forms.TextInput(
        attrs={
        'class':'form-control',
        'id': 'password',
        'placeholder':'Create Your  Password'
        }
    ))
    Retype_Password=forms.CharField(widget=forms.TextInput(
        attrs={
        'class':'form-control',
        'id': 'password',
        'placeholder':'Create Your  Password'
        }
    ))

authentication/views.py
from django.shortcuts import render, redirect
import json

# Create your views here.

def home(request):
    return render(request,"index.html")

def signIn(request):
    if request.method=="POST":
        pass
    return render(request,"sign_in.html")

def signUp(request):
    from .models import UserPasswordTable
    from django.http import HttpResponse
    if request.method=="POST":
        try:
            userPasswordTable = UserPasswordTable(UserName=request.POST.__getitem__('name'), UserEmail=request.POST.__getitem__('email'), Password1=request.POST.__getitem__('passwordConfirmed'))
            userPasswordTable.save()
            json_data=json.dumps({'value':'signed up successfully!'})
            return HttpResponse(json_data)

        except Exception as e:
            json_data=json.dumps({'value':'E-mail is Already taken please sign up other email!'})
            return HttpResponse(json_data)

    return render(request,'sign_up.html')

templates/sign_in.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    {% load i18n %}
    {% load static %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" href="{% static 'assets/img/tscout_logo.png' %}" style="max-height: 10px;">
    <title>T.scout Job description</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Fonts  -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/simple-line-icons.css' %}">
    <!-- CSS Animate -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- Custom styles for this theme -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Feature detection -->
    <script src="{% static 'js/vendor/modernizr-2.6.2.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="{% static 'js/vendor/html5shiv.js' %}"></script>
    <script src="{% static 'js/vendor/respond.min.js' %}"></script>
    <![endif]-->
</head>

<body style="background: white;">
    <section class="container animated fadeInUp">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div id="login-wrapper">
                    <header>
                        <div class="brand">
                            <img src="{% static 'assets/img/tscout_logo.png' %}" style="max-height: 60px;margin-top: 0px;"></img>
                        </div>
                    </header>
                    <div class="panel panel-primary">
                        <div class="panel-body">
                           
                            <div style="font-size: 15px; align-items: center; text-align: center;margin-top: -10px;font-family:Gilroy-Medium;">Account Login</div>
                            <div id="login_p">Login with your appropriate given credentials
                                </div><br>
    
                           
                                <form class="form-horizontal" role="form">
                                <div class="form-group">
                                    <div class="col-md-6">
                                        <input type="text" class="effect-1" placeholder="Enter your Email" autocomplete="off">
                                        <span class="focus-border"></span>
                                    </div>
                                    <div class="col-md-6">
                                        <input type="text" class="effect-1" style="-webkit-text-security: disc;" placeholder="Enter your Password" autocomplete="off">
                                        <span class="focus-border"></span>
                                    </div>
                                    <a href="forgotpassword.html" class="help-block" id="forget-password">forgot your password?</a>
                                </div>
                               
                                <div class="form-group">
                                    <div class="col-md-12 center">
                                        <a href="index.html" class="btn btn-success btn-block" style="color: white; background-color: #26B1FC; width: 245px; margin-left: 151px; margin-top: 15px;">Sign in</a>
                                       <br>
                                   <h4 style="text-align:center;color:#26B1FC;margin-top: -15px; margin-left: -15px;">Or</h4><br>
                                    </div>
                                <div class="card">
                                    <div style="position: absolute;">
                                    <img src="{% static 'assets/img/search.png' %}" style="width: 35px; margin-left: 20px; margin-top: 1px"></img>
                                    <a href="#####" id="signgfl"><span>Continue with Google</span></a>
                                </div>
                                </div><br>
                                <div class="card">
                                    <div style="position: absolute;">
                                    <img src="{% static 'assets/img/facebook.png' %}" style="width: 35px; margin-left: 20px; margin-top: 1px"></img>
                                    <a href="#####" id="signgfl"><span>Continue with Facebook</span></a>
                                </div>
                                </div><br>
                                <div class="card">
                                    <div style="position: absolute;">
                                    <img src="{% static 'assets/img/linkedin.png' %}" style="width: 35px; margin-left: 20px; margin-top: 1px"></img>
                                    <a href="#####" id="signgfl"><span>Continue with Linked</span></a>
                                </div>
                                </div>
                                <a href="pages-sign-up.html" id="Signup">Sign Up for an account</a></div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>
    <!--Global JS-->
    <script src="{% static 'js/vendor/jquery-1.11.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/plugins/pace/pace.min.js' %}"></script>
</body>

</html>

templates/sign_up.html
<!DOCTYPE html>

<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->

<html class="no-js">
<!--<![endif]-->
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
<head>
    <meta charset="utf-8">
    {% load i18n %}
    {% load static %}


    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- icon for web -->

    <link rel="icon" href="{% static 'assets/img/tscout_logo.png' %}" style="max-height: 10px;">

    <title>T.scout Job description</title>

    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> <!-- linked -->

    <!-- CSS Animate -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">


    <!-- Custom styles for this theme -->
    <link rel="stylesheet" href="{% static 'css/custom_new.css' %}">


    <!-- Feature detection -->
    <script src="{% static 'js/custom.js' %}"></script>

    <!-- other dependencies -->
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="{% static 'js/vendor/html5shiv.js' %}"></script>
    <script src="{% static 'js/vendor/respond.min.js' %}"></script>
    <![endif]-->

</head>

<body style="background: white;" >


    <section class="container animated fadeInUp">

        <div class="row">

            <div class="col-md-6 col-md-offset-3">

                <div id="login-wrapper">

                        <div class="brand">

                            <img src="{% static 'assets/img/tscout_logo.png' %}" style="max-height: 60px;margin-top: 0px;"></img>

                        </div>

                        <form ng-app="jdBuilder" ng-controller="jdController" name="signUp" novalidate action="{% url 'authentication:signUp' %}" method="POST" >




                            {% csrf_token %}

                            <div class="panel panel-primary">

                                <div class="panel-body" style="height:700px;">

                                    <div class="col-md-8">

                                        <div class="col-md-8">

                                            <p style="width: 224px; margin-left:  85px;color: #999; margin-top:5px" >Email Address</p>

                                        </div>

                                        <input type="email"  name="email" class="form-control" id="password" ng-model="email" placeholder="Enter Email Address" autocomplete="off" required ng-unique="{key: 'users', property: 'username'}" exist-to ng-pattern="/^[_a-z0-9]+(\.[_a-z0-9]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,8})$/">

                                        <div class="col-md-10">
                                            <span style="width:500px; margin-left:85px;color:red;margin-top:5px;" ng-show="signUp.email.$invalid && signUp.email.$dirty">
                                                <span ng-show="signUp.email.$error.required">Field is required</span>
                                                <span ng-show="signUp.email.$error.email">Invalid email is entered</span>
                                                {% if message %}
                                                <span style="width:500px; margin-left:85px;color:red;margin-top:5px;">{{ message }}</span>
                                                {% endif %}
                                            </span>

                                        </div>

                                    </div>


                                    <div class="col-md-8">

                                        <div class="col-md-8">

                                            <p style="width: 224px; margin-left:  85px;color: #999;margin-top: 5px; ">Name</p>

                                        </div>

                                        <input style="width:100%" type="text" class="form-control" name="name" ng-model="name" id="password" placeholder="Enter Full Name" required >

                                        <div class="col-md-10">

                                            <span style="width:500px;margin-left:85px;color:red;margin-top:5px;" ng-show="signUp.name.$dirty">
                                                <span ng-show="signUp.name.$error.required">Field is required</span>
                                            </span>

                                        </div>

                                    </div>


                                    <div class="col-md-8">

                                        <div class="col-md-8">

                                            <p style="width: 224px; margin-left:  85px;color: #999;margin-top: 5px; ">  Password </p>

                                        </div>

                                        <input type="password" name="firstPassword" ng-model="firstPassword" class="form-control" id="password" placeholder="Create Your  Password" autocomplete="off">

                                    </div>

                                    <div class="col-md-8">

                                        <div class="col-md-8">

                                                <p  id="Names" style="    width: 224px; margin-left:  85px;color: #999;margin-top: 5px; "> Retype Password</p>

                                         </div>

                                         <input type="password" ng-model="passwordConfirmed" name="passwordConfirmed"  class="form-control" id="password" placeholder="Retype Password" autocomplete="off" compare-to="firstPassword">

                                        <div class="col-md-10">

                                            <span style="width:500px; margin-left:85px;color:red;margin-top:5px;" ng-show="signUp.passwordConfirmed.$error.compareTo && signUp.passwordConfirmed.$touched && signUp.firstPassword.$touched">
                                                <span ng-show="signUp.passwordConfirmed.$error">Password doesn't match</span>
                                            </span>

                                        </div>

                                    </div>

                                    <div class="col-md-8">

                                            <input  type="submit" ng-disabled="signUp.email.$invalid || signUp.name.$invalid || signUp.passwordConfirmed.$error.compareTo"value="Sign Up" class="btn btn-success btn-block" style="color: white; background-color: #26B1FC; width: 245px; margin-left: 151px; margin-top: 15px;" >

                                    </div>

                                    <div class="col-md-12">

                                            <center><h4 style="text-align:center;color:#26B1FC;">Or</h4></center>

                                    </div>

                                    <br>
                                <div class="col-md-12" >
                                    <div class="card" style="left: 150px;top: 0px;">

                                        <div style="position: absolute;">

                                            <img src="{% static 'assets/img/search.png' %}" style="width: 35px; margin-left: 20px; margin-top: 1px"></img>

                                            <a href="#####"><span>Continue with Google</span></a>

                                        </div>

                                    </div>

                                    <br>

                                    <div class="card"  style="left: 150px;top: 0px;">

                                        <div style="position: absolute;">

                                            <img src="{% static 'assets/img/facebook.png' %}" style="width: 35px; margin-left: 20px; margin-top: 1px"></img>

                                        <a href="#" ><span>Continue with Facebook</span></a>

                                        </div>

                                    </div>

                                    <br>

                                    <div class="card"   style="left: 150px;top: 0px;" >

                                        <div style="position: absolute;">

                                        <img src="{% static 'assets/img/linkedin.png' %}" style="width: 35px; margin-left: 20px; margin-top: 1px"></img>

                                        <a href="#####" ><span>Continue with Linked</span></a>

                                        </div>

                                    </div>
                                     </div>
                                      <div class="col-md-12" >

                                    <a href="#" id="login_p" style="top:735px;" >Already have an Account? Sign In </a>
                                      </div>
                                </div>

                                </div>
                            </div>
                        </form>
                </div>
            </div>
        </div>
    </section>



    <!--Global JS-->
    <script src="{% static 'javascript/jdBuilder.js' %}"></script>

    <script src="{% static 'javascript/jdController.js' %}"></script>

    <script src="{% static 'js/vendor/jquery-1.11.1.min.js' %}"></script>

    <script src="{% static 'js/plugins/pace/pace.min.js' %}"></script>
</body>
​
</html>